### ISSUE TITLE
I had the same problem, but it worked when it called it from the `cmd` folder (where `main.go` is)

### ISSUE THREAD

**Issue by virak-panha** [KyleBanks/depth#19] opened 2019-12-27 21:00 UTC
I had the same problem, but it worked when it called it from the `cmd` folder (where `main.go` is)

_Originally posted by @ghohmann-asapp in https://github.com/KyleBanks/depth/issues/18#issuecomment-540127086_

**Comment by KyleBanks** [comment] 2021-12-10 10:37
Closing as a duplicate of https://github.com/KyleBanks/depth/issues/18

**Closed** 2021-12-10 10:38 UTC
