### ISSUE TITLE
HELP！FATAL: unable to resolve root package

### ISSUE THREAD

**Issue by V0idk** [KyleBanks/depth#21] opened 2020-12-21 07:39 UTC
FATAL: unable to resolve root package

**Comment by charlseo** [comment] 2021-03-06 10:56
https://github.com/KyleBanks/depth/issues/18#issuecomment-540127086 this might help

**Comment by KyleBanks** [comment] 2021-12-10 10:37
Closing as a duplicate of https://github.com/KyleBanks/depth/issues/18

**Closed by KyleBanks** 2021-12-10 10:37 UTC

**Comment by tzvatot** [comment] 2022-10-27 11:05
Same error
